apiVersion: config.sdcio.dev/v1alpha1
kind: Config
metadata:
  name: intent1-junos
  namespace: default
  labels:
    config.sdcio.dev/targetName: junos-central
    config.sdcio.dev/targetNamespace: default
spec:
  priority: 10
  config:
  - path: /
    value:
      configuration:
        vlans:
          vlan:
          - name: VLAN200
            vlan-id: 200
            l3-interface: irb.200
          - name: VLAN201
            vlan-id: 201
            l3-interface: irb.201
          - name: VLAN202
            vlan-id: 202
            l3-interface: irb.202
          - name: VLAN203
            vlan-id: 203
            l3-interface: irb.203
          - name: VLAN204
            vlan-id: 204
            l3-interface: irb.204
          - name: VLAN205
            vlan-id: 205
            l3-interface: irb.205
          - name: VLAN206
            vlan-id: 206
            l3-interface: irb.206
          - name: VLAN207
            vlan-id: 207
            l3-interface: irb.207
        interfaces:
          interface:
          - name: irb
            unit:                    
            - name: "200"
              family:
                inet:
                  address:
                  - name: "192.168.60.2/30"
            - name: "201"
              family:
                inet:
                  address:
                  - name: "192.168.60.6/30"
            - name: "202"
              family:
                inet:
                  address:
                  - name: "192.168.60.10/30"
            - name: "203"
              family:
                inet:
                  address:
                  - name: "192.168.60.14/30"
            - name: "204"
              family:
                inet:
                  address:
                  - name: "192.168.60.18/30"
            - name: "205"
              family:
                inet:
                  address:
                  - name: "192.168.60.22/30"
            - name: "206"
              family:
                inet:
                  address:
                  - name: "192.168.60.26/30"
            - name: "207"
              family:
                inet:
                  address:
                  - name: "192.168.60.30/30"
          - name: ge-0/0/1
            unit:
            - name: "0"
              family:
                ethernet-switching:
                 interface-mode: trunk
                 vlan:
                 - members:
                   - VLAN200
                   - VLAN201
                   - VLAN202
                   - VLAN203
                   - VLAN204
                   - VLAN205
                   - VLAN206
                   - VLAN207
        routing-instances:
          instance:
          - name: n2
            instance-type: virtual-router
            interface:          
            - name: irb.203 
            - name: irb.207
            protocols:
              bgp:
                group:
                - name: n2
                  type: external
                  local-as:
                    as-number: 65002
                  neighbor:
                  - name: 192.168.60.13
                    peer-as: 65003
                  - name: 192.168.60.29
                    peer-as: 65004
          - name: n4
            instance-type: virtual-router
            interface:
            - name: irb.200
            - name: irb.204
            protocols:
              bgp:
                group:
                - name: n4
                  type: external
                  local-as:
                    as-number: 65005
                  neighbor:
                  - name: 192.168.60.1
                    peer-as: 65006
                  - name: 192.168.60.17
                    peer-as: 65007
          - name: e1
            instance-type: virtual-router
            interface:
            - name: irb.201
            - name: irb.205
            protocols:
              bgp:
                group:
                - name: e1
                  type: external
                  local-as:
                    as-number: 65008
                  neighbor:
                  - name: 192.168.60.5
                    peer-as: 65009
                  - name: 192.168.60.21
                    peer-as: 65010
          - name: f1
            instance-type: virtual-router
            interface:
            - name: irb.202
            - name: irb.206
            protocols:
              bgp:
                group:
                - name: f1
                  type: external
                  local-as:
                    as-number: 65011
                  neighbor:
                  - name: 192.168.60.9
                    peer-as: 65012
                  - name: 192.168.60.25
                    peer-as: 65013