apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: cucp-ran-n2
  namespace: example
spec:
  config: '{"cniVersion":"0.3.1","name": "cucp-ran-n2","plugins":[{"type":"macvlan","capabilities":{"ips":true},"master":"ens19","mode":"bridge","ipam":{"type":"static"}}]}'
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: cucp-ran-f1c
  namespace: example
spec:
  config: '{"cniVersion":"0.3.1","name": "cucp-ran-f1c","plugins":[{"type":"macvlan","capabilities":{"ips":true},"master":"ens19","mode":"bridge","ipam":{"type":"static"}}]}'
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: cucp-ran-e1
  namespace: example
spec:
  config: '{"cniVersion":"0.3.1","name": "cucp-ran-e1","plugins":[{"type":"macvlan","capabilities":{"ips":true},"master":"ens19","mode":"bridge","ipam":{"type":"static"}}]}'