apiVersion: workload.nephio.org/v1alpha1
kind: NFConfig
metadata:
  name: oai-cucp-config
  namespace: example
spec:
  configRefs:
    - apiVersion: workload.nephio.org/v1alpha1
      kind: RANConfig
      metadata:
        name: ranconfig
      spec:
        nrCellId: 1
        gNBID: 12
        gNBName: oai-benetel
    - apiVersion: workload.nephio.org/v1alpha1
      kind: PLMN
      metadata:
        name: plmn
      spec:
        PLMNInfo:
        - plmnID:
            mcc: "208"
            mnc: "99"
          tac: 1
          nssai:
          - sd: ffffff
            sst: 1
