apiVersion: fn.kpt.dev/v1alpha1
kind: ApplyReplacements
metadata:
  name: propagate-namespace
  annotations:
    config.kubernetes.io/local-config: "true"
replacements:
- source:
    kind: ConfigMap
    name: kptfile.kpt.dev
    fieldPath: data.namespace
  targets:
  - select:
      kind: ServiceAccount
    fieldPaths:
    - metadata.namespace
  - select:
      kind: Deployment
    fieldPaths:
    - metadata.namespace
  - select:
      kind: ConfigMap
    fieldPaths:
    - metadata.namespace
