apiVersion: fn.kpt.dev/v1alpha1
kind: ApplyReplacements
metadata:
  name: propagate-namespace
  annotations:
    config.kubernetes.io/local-config: "true"
replacements:
- source:
    kind: ConfigMap
    name: namespace
    fieldPath: data.sriovnamespace
  targets:
  - select:
      kind: SriovNetwork
    fieldPaths:
    - metadata.namespace    
    