apiVersion: fn.kpt.dev/v1alpha1
kind: ApplyReplacements
metadata:
  name: replace-namespace
  annotations:
    config.kubernetes.io/local-config: "true"
replacements:
- source:
    kind: ConfigMap
    name: namespace
    fieldPath: data.namespace
  targets:
  - select:
      kind: Namespace
    fieldPaths:
    - metadata.name   
  - select:
      kind: Config
    fieldPaths:
    - metadata.namespace
  - select:
      kind: NFConfig
    fieldPaths:
    - metadata.namespace
    - spec.configRefs.0.metadata.namespace
    - spec.configRefs.1.metadata.namespace
    - spec.configRefs.2.metadata.namespace
  - select:
      kind: NFDeployment
    fieldPaths:
    - spec.configRefs.[kind=Config].namespace