apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: du-edge-f1
  namespace: example
spec:
  config: '{"cniVersion":"0.3.1","name": "du-edge-f1","plugins":[{"type":"macvlan","capabilities":{"ips":true},
            "master":"ens19","mode":"bridge","ipam":{"type":"static"}}]}'