apiVersion: workload.nephio.org/v1alpha1
kind: NFConfig
metadata:
  name: oai-amf-config
  namespace: example
spec:
  configRefs:
    - apiVersion: cellular.nephio.org/v1alpha1
      kind: PLMN
      metadata:
        name: oai-plmn
      spec:
        plmnInfo:
          - plmnID:
              mcc: "208"
              mnc: "99"
            tac: 1
            nssai:
              - sst: 1
                sd: ffffff
                dnnInfo:
                  - name: internet
                    sessionType: ipv4
                    dns: 172.21.3.100
    - apiVersion: cellular.nephio.org/v1alpha1
      kind: ServedGUAMI
      metadata:
        name: oai-served-guami
      spec:
        - amfID:
            amfPointer: '01'
            amfRegionID: '01'
            amfSetID: '001'
          plmnID:
            mcc: "208"
            mnc: "99"