apiVersion: config.porch.kpt.dev/v1alpha1
kind: PackageVariant
metadata:
  name: core-oai-amf
spec:
  upstream:
    repo: nephio-proxmox-packages
    package: oai-amf-package
    revision: r3
  downstream:
    repo: core
    package: oai-amf
  annotations:
    approval.nephio.org/policy: initial
  injectors:
  - name: core