apiVersion: config.porch.kpt.dev/v1alpha1
kind: PackageVariant
metadata:
  name: metallb-ip-pool-l2-adv
spec:
  upstream:
    repo: nephio-proxmox-packages
    package: metallb-ip-pool-adv-package
    revision: r3
  downstream:
    repo: mgmt
    package: metallb-ip-pool-l2-adv
  annotations:
    approval.nephio.org/policy: initial