apiVersion: config.porch.kpt.dev/v1alpha2
kind: PackageVariantSet
metadata:
  name: workload-crds
spec:
  upstream:
    repo: nephio-proxmox-packages
    package: workload-crds-package
    revision: r3
  targets:
  - repositories:
    - name: core
      packageNames:
        - workload-crds
    - name: edge
      packageNames:
        - workload-crds
    - name: regional
      packageNames:
        - workload-crds
    template:
      annotations:
        approval.nephio.org/policy: initial