apiVersion: config.porch.kpt.dev/v1alpha2
kind: PackageVariantSet
metadata:
  name: oai-ran-operator
spec:
  upstream:
    repo: nephio-proxmox-packages
    package: oai-ran-operator-package
    revision: r3
  targets:
  - repositories:
    - name: edge
      packageNames:
        - oai-ran-operator
    - name: regional
      packageNames:
        - oai-ran-operator
    template:
      annotations:
        approval.nephio.org/policy: initial  