apiVersion: config.porch.kpt.dev/v1alpha1
kind: PackageVariant
metadata:
  name: proxmox-terraform-flux-repo
spec:
  upstream:
    repo: nephio-proxmox-packages
    package: proxmox-tf-repo-package
    revision: r3
  downstream:
    repo: mgmt
    package: proxmox-tf-repo-package
  annotations:
    approval.nephio.org/policy: initial