apiVersion: config.porch.kpt.dev/v1alpha1
kind: PackageVariant
metadata:
  name: edge-frr-router-config
spec:
  upstream:
    repo: nephio-proxmox-packages
    package: remote-site-router-config-package
    revision: r3
  downstream:
    repo: edge
    package: remote-site-router-config-package
  annotations:
    approval.nephio.org/policy: initial    
  pipeline:
    mutators:
    - image: gcr.io/kpt-fn/search-replace:v0.2.0
      selectors:
      - kind: FRRConfiguration
      configMap:
        by-value: FRR_SITE_ROUTER_CONFIG
        put-value: |-
          router bgp 65004 vrf n4vrf
           no bgp ebgp-requires-policy
           no bgp hard-administrative-reset
           no bgp default ipv4-unicast
           no bgp graceful-restart notification
           bgp graceful-restart preserve-fw-state
           no bgp network import-check
           neighbor 192.168.51.3 remote-as 65004
           !
          router bgp 65001 vrf e1vrf
           no bgp ebgp-requires-policy
           no bgp hard-administrative-reset
           no bgp default ipv4-unicast
           no bgp graceful-restart notification
           bgp graceful-restart preserve-fw-state
           no bgp network import-check
           neighbor 192.168.53.3 remote-as 65001
           !
          router bgp 65005 vrf f1vrf
           no bgp ebgp-requires-policy
           no bgp hard-administrative-reset
           no bgp default ipv4-unicast
           no bgp graceful-restart notification
           bgp graceful-restart preserve-fw-state
           no bgp network import-check
           neighbor 192.168.54.4 remote-as 65005
---
apiVersion: config.porch.kpt.dev/v1alpha1
kind: PackageVariant
metadata:
  name: core-frr-router-config
spec:
  upstream:
    repo: nephio-proxmox-packages
    package: remote-site-router-config-package
    revision: r3
  downstream:
    repo: core
    package: remote-site-router-config-package
  annotations:
    approval.nephio.org/policy: initial    
  pipeline:
    mutators:
    - image: gcr.io/kpt-fn/search-replace:v0.2.0
      selectors:
      - kind: FRRConfiguration
      configMap:
        by-value: FRR_SITE_ROUTER_CONFIG
        put-value: |-
          router bgp 65002 vrf n2vrf
           no bgp ebgp-requires-policy
           no bgp hard-administrative-reset
           no bgp default ipv4-unicast
           no bgp graceful-restart notification
           bgp graceful-restart preserve-fw-state
           no bgp network import-check
           neighbor 192.168.55.3 remote-as 65002
           !
          router bgp 65004 vrf n4vrf
           no bgp ebgp-requires-policy
           no bgp hard-administrative-reset
           no bgp default ipv4-unicast
           no bgp graceful-restart notification
           bgp graceful-restart preserve-fw-state
           no bgp network import-check
           neighbor 192.168.56.3 remote-as 65004
---
apiVersion: config.porch.kpt.dev/v1alpha1
kind: PackageVariant
metadata:
  name: regional-frr-router-config
spec:
  upstream:
    repo: nephio-proxmox-packages
    package: remote-site-router-config-package
    revision: r3
  downstream:
    repo: regional
    package: remote-site-router-config-package
  annotations:
    approval.nephio.org/policy: initial    
  pipeline:
    mutators:
    - image: gcr.io/kpt-fn/search-replace:v0.2.0
      selectors:
      - kind: FRRConfiguration
      configMap:
        by-value: FRR_SITE_ROUTER_CONFIG
        put-value: |-
          router bgp 65001 vrf e1vrf
           no bgp ebgp-requires-policy
           no bgp hard-administrative-reset
           no bgp default ipv4-unicast
           no bgp graceful-restart notification
           bgp graceful-restart preserve-fw-state
           no bgp network import-check
           neighbor 192.168.57.3 remote-as 65001
           !
          router bgp 65005 vrf f1vrf
           no bgp ebgp-requires-policy
           no bgp hard-administrative-reset
           no bgp default ipv4-unicast
           no bgp graceful-restart notification
           bgp graceful-restart preserve-fw-state
           no bgp network import-check
           neighbor 192.168.58.3 remote-as 65005
           !
          router bgp 65002 vrf n2vrf
           no bgp ebgp-requires-policy
           no bgp hard-administrative-reset
           no bgp default ipv4-unicast
           no bgp graceful-restart notification
           bgp graceful-restart preserve-fw-state
           no bgp network import-check
           neighbor 192.168.59.3 remote-as 65002