apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: smf-core-n4
  namespace: example
spec:
  config: '{"cniVersion":"0.3.1","name": "smf-core-n4","plugins":[{"type":"macvlan","capabilities":{"ips":true},"master":"ens19","mode":"bridge","ipam":{"type":"static"}}]}'
  