apiVersion: v1
kind: Service
metadata:
  name: nrf-metallb-lb
  namespace: nrf-example
  annotations:
    metallb.universe.tf/address: "10.0.1.246"    
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    workload.nephio.org/oai: nrf
  type: LoadBalancer
