apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: upf-edge-n3
  namespace: upf-example
spec:
  config: '{"cniVersion":"0.3.1","name": "upf-edge-n3","plugins":[{"type":"macvlan","capabilities":{"ips":true},"master":"ens19","mode":"bridge","ipam":{"type":"static"}}]}'
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: upf-edge-n4
  namespace: upf-example
spec:
  config: '{"cniVersion":"0.3.1","name": "upf-edge-n4","plugins":[{"type":"macvlan","capabilities":{"ips":true},"master":"ens19","mode":"bridge","ipam":{"type":"static"}}]}'
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: upf-edge-n6
  namespace: upf-example
spec:
  config: '{"cniVersion":"0.3.1","name": "upf-edge-n6","plugins":[{"type":"macvlan","capabilities":{"ips":true},"master":"ens19","mode":"bridge","ipam":{"type":"static"}}]}'
