apiVersion: workload.nephio.org/v1alpha1
kind: NFDeployment
metadata:
  name: upf-example
  namespace: upf-example
spec:
  provider: upf.openairinterface.org
  capacity:
    maxDownlinkThroughput: 5G
    maxUplinkThroughput: 5G
  parametersRefs:
  - name: oai-upf-config
    apiVersion: workload.nephio.org/v1alpha1
    kind: NFConfig
  interfaces:
  - name: n3
    ipv4:
      address: 192.168.30.3/24
      gateway: 192.168.30.1
    vlanID: 30
  - name: n4
    ipv4:
      address: 192.168.31.3/24
      gateway: 192.168.31.1
    vlanID: 31
  - name: n6
    ipv4:
      address: 172.21.10.2/22
      gateway: 172.21.11.254
    vlanID: 422
  networkInstances:
  - name: vpc-internal
    interfaces:
    - n4
  - name: vpc-internet
    interfaces:
    - n6
  - name: vpc-ran
    interfaces:
    - n3