apiVersion: k0smotron.io/v1beta1
kind: Cluster
metadata:
  name: CLUSTER_NAME
  namespace: k0smotron
spec:
  k0sVersion: k0s_Release_Version # kpt-set: ${k0s-release-version}
  persistence:
    type: emptyDir
  service:
    type: LoadBalancer