apiVersion: config.porch.kpt.dev/v1alpha2
kind: PackageVariantSet
metadata:
  name: multus
spec:
  upstream:
    repo: oai-packages
    package: multus
    revision: main
  targets:
  - repositories:
    - name: controlplane
      packageNames:
        - multus    
    - name: userplane
      packageNames:
        - multus    
    - name: ran
      packageNames:
        - multus    
    template:
      annotations:
        approval.nephio.org/policy: initial