apiVersion: config.porch.kpt.dev/v1alpha1
kind: PackageVariant
metadata:
  name: core-oai-nrf
spec:
  upstream:
    repo: oai-packages
    package: oai-nrf
    revision: main
  downstream:
    repo: controlplane
    package: oai-nrf
  annotations:
    approval.nephio.org/policy: initial
  injectors:
  - name: core