apiVersion: config.porch.kpt.dev/v1alpha2
kind: PackageVariantSet
metadata:
  name: oai-operators-crds
spec:
  upstream:
    repo: oai-packages
    package: oai-cp-operators
    revision: main
  downstream:
    repo: controlplane
    package: oai-cp-operators
  annotations:
    approval.nephio.org/policy: initial
  injectors:
  - name: core