apiVersion: config.porch.kpt.dev/v1alpha1
kind: PackageVariant
metadata:
  name: workload-crds-controlplane
spec:
  upstream:
    repo: oai-packages
    package: workload-crds
    revision: main
  downstream:
    repo: controlplane
    package: workload-crds
  annotations:
    approval.nephio.org/policy: initial
  injectors:
  - name: core