apiVersion: config.porch.kpt.dev/v1alpha1
kind: PackageVariant
metadata:
  name: oai-ranu-operator
spec:
  upstream:
    repo: oai-packages
    package: oai-ran-operator
    revision: main
  downstream:
    repo: userplane
    package: oai-ranu-operator
  annotations:
    approval.nephio.org/policy: initial
  injectors:
  - name: edge