apiVersion: config.porch.kpt.dev/v1alpha1
kind: PackageVariant
metadata:
  name: workload-crds
spec:
  upstream:
    repo: oai-packages
    package: workload-crds
    revision: main
  targets:
  - repositories:
    - name: controlplane
      packageNames:
        - workload-crds
    - name: userplane
      packageNames:
        - workload-crds
    - name: ran
      packageNames:
        - workload-crds
    template:
      annotations:
        approval.nephio.org/policy: initial