apiVersion: v1
kind: ConfigMap
metadata:
  name: network-config
  namespace: porch-system
data:
  network-config.yaml: |
    cniPlugin: macvlan
    amf:
      interfaces: 
        n2:
          ip: "192.168.55.2/24"
          networkAddress: "192.168.55.0/24"
          gw: "192.168.55.1"
          multusParentInterface: "mltus_ens19_106"
    smf:
      interfaces: 
        n4:
          ip: "192.168.56.2/24"
          networkAddress: "192.168.56.0/24"
          gw: "192.168.56.1"
          multusParentInterface: "mltus_ens19_107" 
    upf:
      interfaces: 
        n3:
          ip: "192.168.50.2/24"
          networkAddress: "192.168.50.0/24"
          gw: "192.168.50.1"
          multusParentInterface: "mltus_ens19_101"
        n4:
          ip: "192.168.51.2/24"
          networkAddress: "192.168.51.0/24"
          gw: "192.168.51.1"
          multusParentInterface: "mltus_ens19_102"
        n6:
          ip: "192.168.52.2/24"
          networkAddress: "192.168.52.0/24"
          gw: "192.168.52.1"
          multusParentInterface: "mltus_ens19_103"
    cucp:
      interfaces: 
        n2:
          ip: "192.168.59.2/24"
          networkAddress: "192.168.59.0/24"
          gw: "192.168.59.1"
          multusParentInterface: "mltus_ens19_110"
        e1:
          ip: "192.168.57.2/24"
          networkAddress: "192.168.57.0/24"
          gw: "192.168.57.1"
          multusParentInterface: "mltus_ens19_108"
        f1c:
          ip: "192.168.58.2/24"
          networkAddress: "192.168.58.0/24"
          gw: "192.168.58.1"
          multusParentInterface: "mltus_ens19_109"
    cuup:
      interfaces: 
        n3:
          ip: "192.168.50.3/24"
          networkAddress: "192.168.50.0/24"
          gw: "192.168.50.1"
          multusParentInterface: "mltus_ens19_101"
        e1:
          ip: "192.168.53.2/24"
          networkAddress: "192.168.53.0/24"
          gw: "192.168.53.1"
          multusParentInterface: "mltus_ens19_104"
        f1u:
          ip: "192.168.54.2/24"
          networkAddress: "192.168.54.0/24"
          gw: "192.168.54.1"
          multusParentInterface: "mltus_ens19_105"
    du:
      interfaces:
        f1u:
          ip: "192.168.54.3/24"
          networkAddress: "192.168.54.0/24"
          gw: "192.168.54.1"
          multusParentInterface: "mltus_ens19_105"