apiVersion: config.porch.kpt.dev/v1alpha1
kind: Repository
metadata:
  name: oai-packages
  namespace: default
  labels:
    kpt.dev/repository-access: read-only
    kpt.dev/repository-content: external-blueprints
spec:
  content: Package
  deployment: false
  git:
    branch: r2
    directory: /
    repo: https://github.com/OPENAIRINTERFACE/oai-packages
  type: git
