apiVersion: workload.nephio.org/v1alpha1
kind: NFDeployment
metadata:
  name: cuup-example
  namespace: example
spec:
  provider: cuup.openairinterface.org
  interfaces:
  - name: n3
    ipv4:
      address: 192.168.30.5/24
      gateway: 192.168.30.1
    vlanID: 30
  - name: f1u
    ipv4:
      address: 192.168.32.3/24
      gateway: 192.168.32.1
    vlanID: 32
  - name: e1
    ipv4:
      address: 192.168.33.3/24
      gateway: 192.168.33.1
    vlanID: 33
  networkInstances:
  - name: vpc-ran
    interfaces:
    - n3
  - name: vpc-cudu-f1
    interfaces:
    - f1u
  - name: vpc-cu-e1
    interfaces:
    - e1
  parametersRefs:
  - name: oai-cuup-config
    apiVersion: workload.nephio.org/v1alpha1
    kind: NFConfig